### ISSUE TITLE
Can't change Budget value

### ISSUE THREAD

**Issue by rudism** [Uriopass/TinyCalorie#3]
Running Docker tag 1.0, using Firefox to access.

Seems like trying to enter a different budget doesn't work--trying to type anything or use the up/down controls to change the Budget value gets transposed to the Metabolism value instead and Budget keeps resetting to 1500.

I think there is a hard-coded `metabolism` key in the `updateConf` function that might be the cause.

**Comment by Uriopass** [comment]
Uploaded tag 1.1 with the fix!
